import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import Sidebar from "@/app/dashboard/(components)/Sidebar";
import Navbar from "@/app/dashboard/(components)/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({children}: { children: React.ReactNode }) {
    return (

        <html lang="en">
        <body className={inter.className}>
        <main className="flex min-h-screen">

                <Sidebar/>

            <section className="flex flex-col bg-accent w-full p-6 gap-5">
                <Navbar/>
                {children}
            </section>
        </main>

        </body>
        </html>

    )
}